FROM python:3.12.4-slim

WORKDIR /text_generator_container
# Copy service account key
COPY keen-dispatch-385408-7150201568b0.json /app/key.json

COPY shared/ ./shared/
RUN pip3 install ./shared

# Set environment variable
ENV GOOGLE_APPLICATION_CREDENTIALS=/app/key.json


COPY text_generator/ .

# Specify the command to run your application
CMD ["python", "main.py"]