FROM python:3.12.4-slim

WORKDIR /text_generator_container

COPY keen-dispatch-385408-7150201568b0.json /app/key.json

COPY shared/ ./shared/
RUN pip3 install ./shared


ENV GOOGLE_APPLICATION_CREDENTIALS=/app/key.json


COPY text_generator/ .

CMD ["python", "main.py"]